services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      DB_URL: ${DB_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
      VPS_IP: ${VPS_IP}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dosatsu-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dosatsu_poll_postgres_data:/var/lib/postgresql/data
    networks:
      - dosatsu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dosatsuuser -d dosatsu"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dosatsu-network:
    driver: bridge

volumes:
  dosatsu_poll_postgres_data:
    driver: local
