services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dosatsu-app
    ports:
      - "3001:3001"
    env_file:
      - .env.development 
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dosatsu-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:17-alpine
    container_name: dosatsu-poll-postgres
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - dosatsu_poll_postgres_data:/var/lib/postgresql/data
    networks:
      - dosatsu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dosatsuuser -d dosatsu"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dosatsu-network:
    driver: bridge

volumes:
  dosatsu_poll_postgres_data:
    driver: local